# LuciferAI Ecosystem - Support Development
# These links will appear on the GitHub "Sponsor" button

github: [GareBear99]
ko_fi: GareBear99
buy_me_a_coffee: GareBear99
custom: ["https://paypal.me/LuciferAIDev"]
